name: Checkout

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'タグに付ける別名、カンマ区切り'
        required: false
        default: 'latest'
      push:
        description: 'push するかどうか'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  minio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'タグを準備'
        id: tags
        run: echo "tags=$(./tags.sh)" >>$GITHUB_OUTPUT
        env:
          PACKAGE: checkout
          CSV_LIST: "${{ inputs.tags }}"
          REPO_OWNER: ${{ github.repository_owner }}

      - uses: docker/build-push-action@v5
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          context: checkout
          tags: ${{ steps.tags.outputs.tags }}
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
