name: Python

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Python のバージョン (e.g. 3.13)'
        required: true
      tags:
        description: 'タグに付ける別名、カンマ区切り (e.g. 2024.11.0)'
        required: true
        default: ''
      push:
        description: 'push するかどうか'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  ds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'タグを準備'
        id: tags
        run: echo "tags=$(./tags.sh)" >>$GITHUB_OUTPUT
        env:
          PACKAGE: python-ds
          CSV_LIST: "${{ inputs.tags }},latest"
          REPO_OWNER: ${{ github.repository_owner }}

      - uses: docker/build-push-action@v5
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          context: python/ds
          build-args: VERSION=${{ inputs.version }}
          tags: ${{ steps.tags.outputs.tags }}
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
